// Predefined niches and creator types for the creator profile setup

export const NICHES: string[] = [
  // Lifestyle
  'Lifestyle',
  'Daily Vlogs',
  'Family',
  'Couple Content',
  'Parenting',
  'Home Organization',
  'Minimalism',
  'Luxury Lifestyle',
  'Apartment Living',
  'Van Life',
  'Digital Nomad',
  'Rural Lifestyle',

  // Fashion & Beauty
  'Fashion',
  "Men's Fashion",
  "Women's Fashion",
  'Streetwear',
  'Luxury Fashion',
  'Sustainable Fashion',
  'Thrift Fashion',
  'Makeup',
  'Skincare',
  'Hair Care',
  'Nail Art',
  'Fragrance',
  'Grooming',
  'Personal Styling',
  'Fashion Reviews',

  // Food & Cooking
  'Cooking',
  'Baking',
  'Home Chef',
  'Street Food',
  'Food Reviews',
  'Restaurant Reviews',
  'Fine Dining',
  'Healthy Recipes',
  'Vegan',
  'Vegetarian',
  'BBQ & Grilling',
  'Coffee',
  'Tea',
  'Cocktails & Mocktails',
  'Food Challenges',
  'Mukbang',

  // Fitness & Health
  'Fitness',
  'Bodybuilding',
  'Weight Loss',
  'Yoga',
  'Pilates',
  'Calisthenics',
  'CrossFit',
  'Running',
  'Cycling',
  'Swimming',
  'Martial Arts',
  'Nutrition',
  'Mental Health',
  'Meditation',
  'Wellness',
  'Biohacking',

  // Travel
  'Travel Vlogs',
  'Luxury Travel',
  'Budget Travel',
  'Adventure Travel',
  'Solo Travel',
  'Backpacking',
  'Road Trips',
  'Camping',
  'Hiking',
  'Hotel Reviews',
  'Airline Reviews',
  'Destination Guides',

  // Technology
  'Tech Reviews',
  'Smartphones',
  'Laptops',
  'AI',
  'Programming',
  'Web Development',
  'Cybersecurity',
  'Cloud Computing',
  'SaaS',
  'Startups',
  'Gadgets',
  'Smart Home',
  'Robotics',
  'IoT',
  'AR/VR',
  'Consumer Electronics',

  // Gaming
  'PC Gaming',
  'Mobile Gaming',
  'Console Gaming',
  'Esports',
  'Game Streaming',
  'Walkthroughs',
  'Game Reviews',
  'Speedruns',
  'Minecraft',
  'GTA',
  'Valorant',
  'BGMI/PUBG',
  'Free Fire',
  'Fortnite',
  'Roblox',
  'Chess',

  // Finance & Business
  'Personal Finance',
  'Investing',
  'Stock Market',
  'Cryptocurrency',
  'Mutual Funds',
  'Real Estate',
  'Business',
  'Entrepreneurship',
  'Side Hustles',
  'Career Advice',
  'Freelancing',
  'E-commerce',
  'Dropshipping',
  'Marketing',
  'Sales',

  // Education
  'Mathematics',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'Engineering',
  'UPSC',
  'JEE',
  'NEET',
  'CAT',
  'IELTS',
  'English Speaking',
  'Coding',
  'Language Learning',
  'Study Tips',
  'Productivity',

  // Entertainment
  'Comedy',
  'Memes',
  'Stand-up Comedy',
  'Pranks',
  'Reactions',
  'Challenges',
  'Storytelling',
  'Short Films',
  'Skits',
  'Interviews',
  'Podcasts',

  // Music
  'Singing',
  'Music Production',
  'Instrumental',
  'Guitar',
  'Piano',
  'Violin',
  'Rap',
  'DJ',
  'Covers',
  'Original Music',
  'Beatboxing',

  // Dance
  'Dance Covers',
  'Choreography',
  'Hip-Hop',
  'Classical Dance',
  'Contemporary',
  'Bollywood Dance',
  'K-Pop Dance',
  'Freestyle',

  // Photography & Videography
  'Photography',
  'Mobile Photography',
  'Cinematography',
  'Drone Photography',
  'Photo Editing',
  'Video Editing',
  'Filmmaking',
  'Color Grading',

  // Art & Creativity
  'Digital Art',
  'Painting',
  'Sketching',
  'Calligraphy',
  'DIY',
  'Crafts',
  'Pottery',
  'Sculpture',
  'Animation',
  'Graphic Design',
  '3D Art',

  // Automobile
  'Car Reviews',
  'Bike Reviews',
  'EVs',
  'Supercars',
  'Motorsports',
  'Car Modifications',
  'Road Tests',
  'Auto News',

  // Pets & Animals
  'Dogs',
  'Cats',
  'Exotic Pets',
  'Pet Training',
  'Aquarium',
  'Wildlife',
  'Horse Riding',

  // Sports
  'Cricket',
  'Football',
  'Basketball',
  'Tennis',
  'Badminton',
  'Kabaddi',
  'Formula 1',
  'Golf',
  'Athletics',
  'Wrestling',
  'Boxing',

  // Science & Knowledge
  'Space',
  'Astronomy',
  'History',
  'Geography',
  'Psychology',
  'Philosophy',
  'Economics',
  'Politics',
  'Current Affairs',

  // Books & Writing
  'Book Reviews',
  'Book Summaries',
  'Self-Help',
  'Fiction',
  'Poetry',
  'Writing Tips',
  'Journaling',

  // Career & Professional
  'LinkedIn Tips',
  'Resume Reviews',
  'Interview Preparation',
  'HR',
  'Corporate Life',
  'Consulting',
  'Management',
  'Public Speaking',

  // Home & Living
  'Interior Design',
  'Home Decor',
  'Gardening',
  'DIY Home',
  'Smart Homes',

  // Relationship & Personal Development
  'Dating Advice',
  'Marriage',
  'Self Improvement',
  'Confidence',
  'Communication',
  'Personality Development',

  // Parenting & Kids
  'Parenting Tips',
  'Kids Activities',
  'Child Education',
  'Mom Blogger',
  'Dad Blogger',

  // Spirituality & Religion
  'Spiritual Growth',
  'Yoga Philosophy',
  'Religious Content',
  'Astrology',
  'Tarot',
  'Numerology',

  // News & Media
  'News',
  'Political Commentary',
  'Business News',
  'Tech News',
  'Sports News',
  'Fact Checking',

  // Local & Regional
  'City Guides',
  'Local Food',
  'Regional Culture',
  'Regional Language Content',

  // Professional Creator Categories
  'UGC Creator',
  'Brand Ambassador',
  'Product Reviewer',
  'Affiliate Marketer',
  'Live Streamer',
  'Podcast Host',
  'Webinar Host',
  'Course Creator',
  'Newsletter Creator',
  'Community Builder',

  // B2B & Industry Experts
  'Doctors',
  'Lawyers',
  'Engineers',
  'Architects',
  'Chartered Accountants',
  'Product Managers',
  'UX/UI Designers',
  'Recruiters',

  // Emerging Niches
  'AI Tools',
  'Prompt Engineering',
  'No-Code',
  'Web3',
  'Blockchain',
  'Creator Economy',
  'Remote Work',
  'Sustainability',
  'Climate Tech',
  'Longevity',
  'Smart Gadgets',
  'Digital Products',
  'Indie Hacking',
  'Solopreneurship',
];

export const CREATOR_TYPES: string[] = [
  'Content Creator',
  'Influencer',
  'UGC Creator',
  'Brand Ambassador',
  'Affiliate Creator',
  'Educator',
  'Coach / Mentor',
  'Blogger / Writer',
  'Podcaster',
  'Streamer',
  'Gamer',
  'Photographer',
  'Videographer / Filmmaker',
  'Artist / Designer',
  'Musician / Singer',
  'Dancer',
  'Comedian',
  'Actor / Performer',
  'Public Speaker',
  'Entrepreneur',
  'Consultant',
  'Community Builder',
  'Product Reviewer',
  'Voice Artist',
  'AI Creator',
  'Virtual Creator (VTuber/Avatar)',
  'Professional Expert',
  'NGO / Social Impact Creator',
];
